# Generated by Django 3.0.4 on 2020-03-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Day_of_Input', models.DateField()),
                ('GS_2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('GS_15', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Ferreira', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Luphohlo_Daily_Level', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Mkinkomo_Reservor_Daily_Level', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
