# Generated by Django 3.0.4 on 2020-03-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0003_auto_20200312_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='Ferreira',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='GS_15',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='GS_2',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='Luphohlo_Daily_Level',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='Mkinkomo_Reservor_Daily_Level',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
