# Generated by Django 3.0.4 on 2020-03-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0005_auto_20200312_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='Day_of_Input',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
