# Generated by Django 3.0.4 on 2020-03-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0007_auto_20200312_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='Ferreira',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='inflow',
            name='GS_15',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='inflow',
            name='GS_2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='inflow',
            name='Luphohlo_Daily_Level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='inflow',
            name='Mkinkomo_Reservor_Daily_Level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
