# Generated by Django 3.0.4 on 2020-03-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0009_auto_20200312_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflow',
            old_name='Mkinkomo_Reservor_Daily_Level',
            new_name='Mkinkomo_Reservoir_Daily_Level',
        ),
    ]
